spring:
  application:
    name: file-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://config-service}
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
      uri: ${CONFIG_SERVICE_URI:lb://config-service}
      fail-fast: true
      enabled: true
      label: test
      profile: test

server:
  port: ${PORT:7000}
file:
  upload:
    dir: ${FILE_UPLOAD_DIR:/Users/kaanyilmaz/Documents/upload}


