# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Cache Maven packages
      uses: actions/cache@v2.1.4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build tasarlasat-fileservice
      env:
        SUPER_SECRET: ${{ secrets.CR_PAT }}
      run: |
        docker build --build-arg SUPER_SECRET=$SUPER_SECRET --tag ghcr.io/yykaan/tasarlasat-fileservice:latest -f Dockerfile .
        docker push ghcr.io/yykaan/tasarlasat-fileservice:latest






